apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: esteemed

resources:
  - ../../base
  - namespace.yaml

images:
  - name: esteemed
    newName: ghcr.io/vicmanager/esteemed
    newTag: latest

replicas:
  - name: esteemed
    count: 3
